Repository Room-In-Us/Room-In-Us-Front, pull requests merged in 2024-10, with the labels that each got.

#28 Style: 글쓰기 페이지 디자인 수정
  src/pages/BoardMorePage.jsx
  src/pages/BoardWritePage.jsx
Labels: 🎨 Html&css

#31 Style: 헤더, 로그인 페이지 반응형 구현
  package-lock.json
  package.json
  src/assets/icons/common/cancelIcon.svg
  src/assets/icons/common/menuIcon.svg
  src/components/common/Header.jsx
  src/components/location/CafeArea.jsx
  src/components/location/InitialArea.jsx
  src/components/location/LocationContent.jsx
  src/components/location/StationArea.jsx
  src/components/location/ThemeArea.jsx
  src/hooks/useDevice.js
  src/pages/LocationPage.jsx
  src/pages/LoginPage.jsx
Labels: 🎨 Html&css

#33 Feat: API 연결 세팅 및 숙련도 목록조회 API 연결
  .vite/deps/_metadata.json
  .vite/deps/package.json
  package-lock.json
  package.json
  src/App.jsx
  src/apis/API.jsx
  src/apis/theme/getProficiencyListAPI.js
  src/components/map/MyMap.jsx
  src/components/map/NaverMapContainer.jsx
  src/pages/LevelInfoPage.jsx
  src/pages/LevelPage.jsx
  src/pages/MapPage.jsx
  vite.config.js
Labels: 📬 API

#35 Fix: netlify 에러 해결
  _redirects
Labels: 🐞 BugFix

#36 Fix: netlify 에러 해결
  netlify.toml
Labels: 🐞 BugFix

#40 Feature: 장소페이지 디자인 수정
  package-lock.json
  package.json
  src/App.jsx
  src/assets/icons/common/logo.svg
  src/assets/icons/loginPage/googleLogo.svg
  src/assets/icons/loginPage/kakaoLogo.svg
  src/assets/icons/mainPage/enterIcon.svg
  src/assets/icons/mainPage/searchIcon.svg
  src/assets/images/locationPage/locationBackground.png
  src/assets/images/locationPage/locationButton.png
  src/assets/images/locationPage/marker.png
  src/assets/images/locationPage/pettern1.png
  src/assets/images/locationPage/pettern2.png
  src/assets/images/locationPage/pettern3.png
  src/assets/images/locationPage/pettern4.png
  src/assets/images/locationPage/pettern5.png
  src/assets/images/locationPage/pettern6.png
  src/assets/images/locationPage/pettern7.png
  src/assets/images/locationPage/pettern8.png
  src/assets/images/locationPage/spotRectangle.png
  src/assets/images/locationPage/spotSquare1.png
  src/assets/images/locationPage/spotSquare2.png
  src/components/common/Header.jsx
  src/components/location/InitialArea.jsx
  src/components/location/LocationContent.jsx
  src/components/location/map/GoogleMaps.jsx
  src/components/location/map/googleMapStyles.js
  src/components/map/MyMap.jsx
  src/components/map/NaverMapContainer.jsx
  src/layout/MainLayOut.jsx
  src/main.jsx
  src/pages/LocationPage.jsx
  src/pages/LoginPage.jsx
  src/pages/MainPage.jsx
  src/pages/MapPage.jsx
  src/recoil/atoms/locationAtom.jsx
  src/recoil/selectors/locationSelector.jsx
  src/utils/ScrollToTop.js
Labels: ✨ Feature

#42 Setting: scrolltotop 파일 이름 수정
  src/main.jsx
  src/utils/scrollToTopFunc.js
Labels: ⚙ Setting
