Repository Room-In-Us/Room-In-Us-Front, pull requests merged in 2025-04, with the labels that each got.

#89 Feat: 성향조사 페이지 레이아웃 구현
  src/app/App.jsx
  src/features/auth/ui/AgreeSection.jsx
  src/features/survey/model/surveyAtom.jsx
  src/features/survey/model/surveyGenreList.js
  src/features/survey/model/surveyPreferenceList.js
  src/features/survey/ui/SurveyCompleteSection.jsx
  src/features/survey/ui/SurveyGenreSection.jsx
  src/features/survey/ui/SurveyHeadcountSection.jsx
  src/features/survey/ui/SurveyInfoSection.jsx
  src/features/survey/ui/SurveyPositionSection.jsx
  src/features/survey/ui/SurveyPreferenceSection.jsx
  src/features/survey/ui/SurveyProficiencySection.jsx
  src/features/survey/ui/SurveyTag.jsx
  src/pages/LoginPage.jsx
  src/pages/SurveyPage.jsx
  src/shared/assets/icons/survey/leftArrowIcon.svg
  src/shared/assets/icons/survey/rightArrowIcon.svg
  src/shared/assets/images/survey/surveyImage.png
  src/shared/components/ContentCard.jsx
  src/widgets/MainLayOut.jsx
Labels: ✨ Feature

#92 Feat: 성향조사 API 연결
  src/features/auth/api/authAPI.js
  src/features/auth/ui/CompleteSection.jsx
  src/features/survey/api/surveyAPI.js
  src/features/survey/model/surveyAtom.jsx
  src/features/survey/model/surveyGenreList.js
  src/features/survey/model/surveyPreferenceList.js
  src/features/survey/ui/SurveyGenreSection.jsx
  src/features/survey/ui/SurveyHeadcountSection.jsx
  src/features/survey/ui/SurveyInfoSection.jsx
  src/features/survey/ui/SurveyPositionSection.jsx
  src/features/survey/ui/SurveyPreferenceSection.jsx
  src/features/survey/ui/SurveyProficiencySection.jsx
Labels: ✨ Feature, 📬 API

#93 Feat: 성향조사 페이지 반응형 구현
  src/app/API.jsx
  src/features/survey/model/surveyAtom.jsx
  src/features/survey/model/surveyGenreList.js
  src/features/survey/ui/QuitModal.jsx
  src/features/survey/ui/SurveyCompleteSection.jsx
  src/features/survey/ui/SurveyGenreSection.jsx
  src/features/survey/ui/SurveyHeadcountSection.jsx
  src/features/survey/ui/SurveyInfoSection.jsx
  src/features/survey/ui/SurveyPositionSection.jsx
  src/features/survey/ui/SurveyPreferenceSection.jsx
  src/features/survey/ui/SurveyProficiencySection.jsx
  src/features/survey/ui/SurveyTag.jsx
  src/pages/LoginPage.jsx
  src/pages/SignupPage.jsx
  src/pages/SurveyPage.jsx
  src/shared/assets/icons/survey/modalCancelIcon.svg
  src/shared/assets/icons/survey/modalCautionIcon.svg
  src/shared/components/Header.jsx
  src/widgets/MainLayOut.jsx
Labels: ✨ Feature, 🎨 Html&css

#94 [BUG] 바텀 시트 지역 필터링 오류 해결 (#85)
  src/features/genre/ui/GenreContentSection.jsx
  src/features/genre/ui/GenreTabSection.jsx
  src/shared/components/BottomSheet.jsx
  src/shared/components/filter/FilterStyles.js
  src/shared/components/filter/PeopleFilter.jsx
  src/shared/components/filter/RegionFilter.jsx
  src/shared/components/filter/SortFilter.jsx
  src/shared/utils/filterUtils.js
Labels: 🐞 BugFix

#96 [Style] 장르 페이지 탭 디자인 수정 (#95)
  src/features/genre/ui/GenreTabSection.jsx
Labels: 🎨 Html&css

#98 [FEAT] 필터 기능 추가 및 오류 수정 (#97)
  src/features/genre/api/genreAPI.js
  src/features/genre/ui/GenreContentSection.jsx
  src/shared/components/BottomSheet.jsx
  src/shared/components/filter/OptionList.js
  src/shared/components/filter/PeopleFilter.jsx
  src/shared/components/filter/SortFilter.jsx
Labels: ✨ Feature, 🐞 BugFix

#103 [FEAT] 필터 드롭다운 효과 구현 (#102)
  src/shared/components/filter/FilterStyles.js
  src/shared/components/filter/PeopleFilter.jsx
  src/shared/components/filter/RegionFilter.jsx
  src/shared/components/filter/SortFilter.jsx
Labels: ✨ Feature

#108 [FEAT] 구글맵 API 연결
  src/features/location/api/getLocationListAPI.js
  src/features/location/api/getThemeInfoAPI.js
  src/features/location/api/getZoneInfoAPI.js
  src/features/location/model/locationAtom.jsx
  src/features/location/ui/CafeArea.jsx
  src/features/location/ui/LocationContent.jsx
  src/features/location/ui/StationArea.jsx
  src/features/location/ui/StationCard.jsx
  src/features/location/ui/StoreCard.jsx
  src/features/location/ui/ThemeArea.jsx
  src/features/location/ui/ThemeInfo.jsx
  src/features/location/ui/map/GoogleMapComponent.jsx
  src/features/location/ui/map/GoogleMaps.jsx
  src/pages/LocationPage.jsx
  src/shared/assets/icons/location/stationLine/line1.svg
  src/shared/assets/icons/location/stationLine/line10.svg
  src/shared/assets/icons/location/stationLine/line11.svg
  src/shared/assets/icons/location/stationLine/line12.svg
  src/shared/assets/icons/location/stationLine/line13.svg
  src/shared/assets/icons/location/stationLine/line14.svg
  src/shared/assets/icons/location/stationLine/line15.svg
  src/shared/assets/icons/location/stationLine/line16.svg
  src/shared/assets/icons/location/stationLine/line17.svg
  src/shared/assets/icons/location/stationLine/line18.svg
  src/shared/assets/icons/location/stationLine/line19.svg
  src/shared/assets/icons/location/stationLine/line2.svg
  src/shared/assets/icons/location/stationLine/line20.svg
  src/shared/assets/icons/location/stationLine/line21.svg
  src/shared/assets/icons/location/stationLine/line22.svg
  src/shared/assets/icons/location/stationLine/line23.svg
  src/shared/assets/icons/location/stationLine/line24.svg
  src/shared/assets/icons/location/stationLine/line3.svg
  src/shared/assets/icons/location/stationLine/line4.svg
  src/shared/assets/icons/location/stationLine/line5.svg
  src/shared/assets/icons/location/stationLine/line6.svg
  src/shared/assets/icons/location/stationLine/line7.svg
  src/shared/assets/icons/location/stationLine/line8.svg
  src/shared/assets/icons/location/stationLine/line9.svg
  src/shared/utils/stationLineUtils.js
Labels: ✨ Feature, 📬 API
