Repository Room-In-Us/Room-In-Us-Front, pull requests merged in 2025-07, with the labels that each got.

#142 Feat: 내가 작성한 후기 마이페이지 ui 구현 & api 연결 (#140)
  src/features/like/api/themeLikeAPI.js
  src/features/mypage/api/myReviewAPI.js
  src/features/mypage/model/reviewDataList.js
  src/features/mypage/model/reviewSortAtom.js
  src/features/mypage/ui/favorites/FavoriteDropDown.jsx
  src/features/mypage/ui/favorites/HeaderSection.jsx
  src/features/mypage/ui/reviews/ReviewCard.jsx
  src/features/mypage/ui/reviews/ReviewCardSection.jsx
  src/features/mypage/ui/reviews/ReviewDropDown.jsx
  src/pages/myPage/FavoritesPage.jsx
  src/pages/myPage/ReviewsPage.jsx
Labels: ✨ Feature, 📬 API

#148 Feat: 마이페이지 - 예약한 방탈출 목록 구현 (#147)
  src/features/mypage/api/reservationAPI.js
  src/features/mypage/model/reservationAtom.js
  src/features/mypage/model/reservationDataList.js
  src/features/mypage/ui/reservations/CalendarSection.jsx
  src/features/mypage/ui/reservations/ReservationDropDown.jsx
  src/features/mypage/ui/reservations/ReservedCard.jsx
  src/features/mypage/ui/reservations/ScheduleSection.jsx
  src/pages/myPage/ReservationsPage.jsx
  src/shared/assets/icons/common/more.svg
  src/shared/assets/icons/myPage/pen.svg
  src/shared/assets/icons/myPage/thumbsup.svg
  src/shared/assets/icons/myPage/trash.svg
  src/shared/assets/icons/myPage/write.svg
Labels: ✨ Feature, 📬 API

#157 Feat: 마이 페이지 일부 반응형 구현
  src/features/mypage/ui/preferences/GenreSection.jsx
  src/features/mypage/ui/preferences/HeadcountSection.jsx
  src/features/mypage/ui/preferences/InfoSection.jsx
  src/features/mypage/ui/preferences/PositionSection.jsx
  src/features/mypage/ui/preferences/PreferenceSection.jsx
  src/features/mypage/ui/preferences/ProficiencySection.jsx
  src/features/mypage/ui/preferences/SurveyTag.jsx
  src/pages/NotFoundPage.jsx
  src/pages/myPage/MyPage.jsx
  src/pages/myPage/PreferencesPage.jsx
Labels: 🎨 Style

#159 Feat: 테마 상세 페이지 반응형 구현
  src/features/mypage/ui/reservations/ReservationDropDown.jsx
  src/features/survey/ui/QuitModal.jsx
  src/features/themeDetail/ui/PriceTable.jsx
  src/features/themeDetail/ui/SummaryInfoCard.jsx
  src/features/themeDetail/ui/ThemeInfoSection.jsx
  src/features/themeDetail/ui/ThemeOverviewCard.jsx
  src/features/themeDetail/ui/ThemeReview.jsx
  src/features/themeDetail/ui/ThemeReviewSection.jsx
  src/pages/ThemeDetailPage.jsx
  src/shared/assets/icons/common/more.svg
  src/shared/assets/icons/survey/modalCancelIcon.svg
  src/shared/assets/icons/themeDetail/pencilIcon.svg
  src/shared/components/Header.jsx
Labels: 🎨 Style

#161 Feat: 내가 찜한 방탈출 마이페이지 인원수 정렬 기능 추가 (#160)
  src/features/mypage/model/favoriteAtom.js
  src/features/mypage/ui/favorites/ContentCardSection.jsx
  src/features/mypage/ui/favorites/FavoriteDropDown.jsx
  src/pages/myPage/FavoritesPage.jsx
  src/shared/styles/FilterStyles.js
Labels: ✨ Feature
