Repository Room-In-Us/Room-In-Us-Front, pull requests merged in 2025-05, with the labels that each got.

#110 Bug: 장르 페이지 버그 수정 (#107)
  src/features/genre/api/genreAPI.js
  src/features/genre/ui/GenreContentSection.jsx
  src/shared/assets/icons/common/chevrondoubleleft.svg
  src/shared/assets/icons/common/chevrondoubleright.svg
  src/shared/components/CustomPagination.jsx
  src/shared/components/filter/FilterStyles.js
  src/shared/components/filter/RegionFilter.jsx
Labels: 🐞 BugFix

#113 Feat: 테마 상세 페이지 레이아웃
  src/app/App.jsx
  src/features/location/ui/LocationContentCard.jsx
  src/features/themeDetail/model/reviewAtom.jsx
  src/features/themeDetail/ui/ReviewWriteModal.jsx
  src/features/themeDetail/ui/ThemeInfoSection.jsx
  src/features/themeDetail/ui/ThemeOverviewCard.jsx
  src/pages/ThemeDetailPage.jsx
  src/shared/assets/icons/themeDetail/infoIcon.svg
  src/shared/assets/icons/themeDetail/leftArrow.svg
  src/shared/assets/icons/themeDetail/shareIcon.svg
  src/shared/components/ContentCard.jsx
Labels: ✨ Feature

#115 Feat: 테마상세 페이지 레이아웃
  src/features/location/ui/StationCard.jsx
  src/features/themeDetail/ui/PriceTable.jsx
  src/features/themeDetail/ui/SummaryInfoCard.jsx
  src/features/themeDetail/ui/ThemeInfoSection.jsx
  src/features/themeDetail/ui/ThemeReview.jsx
  src/features/themeDetail/ui/ThemeReviewSection.jsx
  src/shared/assets/icons/themeDetail/blueStar.svg
  src/shared/assets/icons/themeDetail/genreIcon.svg
  src/shared/assets/icons/themeDetail/horrorIcon.svg
  src/shared/assets/icons/themeDetail/levelIcon.svg
  src/shared/assets/icons/themeDetail/playTimeIcon.svg
  src/shared/assets/icons/themeDetail/ratingStar.svg
  src/shared/assets/icons/themeDetail/recommendMemberIcon.svg
  src/shared/assets/icons/themeDetail/reviewEscapeIcon.svg
  src/shared/assets/icons/themeDetail/reviewEvalutionIcon.svg
  src/shared/assets/icons/themeDetail/reviewHintIcon.svg
  src/shared/assets/icons/themeDetail/reviewMemberIcon.svg
  src/shared/assets/icons/themeDetail/reviewTimeIcon.svg
Labels: ✨ Feature

#117 Feat: 마이페이지 일부 레이아웃
  src/app/App.jsx
  src/features/mypage/api/surveyAPI.js
  src/features/mypage/model/surveyAtom.jsx
  src/features/mypage/model/surveyGenreList.js
  src/features/mypage/model/surveyPreferenceList.js
  src/features/mypage/ui/preferences/GenreSection.jsx
  src/features/mypage/ui/preferences/HeadcountSection.jsx
  src/features/mypage/ui/preferences/InfoSection.jsx
  src/features/mypage/ui/preferences/PositionSection.jsx
  src/features/mypage/ui/preferences/PreferenceSection.jsx
  src/features/mypage/ui/preferences/ProficiencySection.jsx
  src/features/mypage/ui/preferences/SurveyTag.jsx
  src/features/survey/ui/SurveyPreferenceSection.jsx
  src/pages/LoginPage.jsx
  src/pages/MyPage.jsx
  src/pages/SurveyPage.jsx
  src/pages/myPage/FavoritesPage.jsx
  src/pages/myPage/PreferencesPage.jsx
  src/pages/myPage/ReservationsPage.jsx
  src/pages/myPage/ReviewsPage.jsx
  src/shared/assets/icons/myPage/leftArrow.svg
  src/shared/assets/icons/myPage/rightArrow.svg
  src/shared/assets/icons/myPage/updateIcon.svg
Labels: ✨ Feature

#118 Feat: 후기 작성 모달 UI 구현 (#114)
  package-lock.json
  package.json
  src/features/level/ui/LevelTabSection.jsx
  src/features/levelInfo/ui/RangeItem.jsx
  src/features/levelInfo/ui/RangeSection.jsx
  src/features/review/modal/reviewDataList.js
  src/features/review/ui/EscapeResultDetails.jsx
  src/features/review/ui/EscapeTimePicker.jsx
  src/features/review/ui/FlexibleRangeSelector.jsx
  src/features/review/ui/HintCounter.jsx
  src/features/review/ui/InputBox.jsx
  src/features/review/ui/PlayerBoxSection.jsx
  src/features/review/ui/RangeItem.jsx
  src/features/review/ui/ReviewDropdown.jsx
  src/features/review/ui/ReviewFirst.jsx
  src/features/review/ui/ReviewLast.jsx
  src/features/review/ui/ReviewSecond.jsx
  src/features/review/ui/ReviewThird.jsx
  src/features/review/ui/StarRating.jsx
  src/features/review/ui/ToggleCheckBox.jsx
  src/features/review/ui/VisitDatePicker.jsx
  src/features/themeDetail/model/reviewAtom.jsx
  src/features/themeDetail/ui/ReviewWriteModal.jsx
  src/shared/assets/icons/common/circleinfo.svg
  src/shared/assets/icons/reviewWrite/boldline.svg
  src/shared/assets/icons/reviewWrite/checkbox.svg
  src/shared/assets/icons/reviewWrite/clock.svg
  src/shared/assets/icons/reviewWrite/closeicon.svg
  src/shared/assets/icons/reviewWrite/date.svg
  src/shared/assets/icons/reviewWrite/delay.svg
  src/shared/assets/icons/reviewWrite/disabledminus.svg
  src/shared/assets/icons/reviewWrite/disabledplus.svg
  src/shared/assets/icons/reviewWrite/giveup.svg
  src/shared/assets/icons/reviewWrite/likeIcon.svg
  src/shared/assets/icons/reviewWrite/line.svg
  src/shared/assets/icons/reviewWrite/malfunction.svg
  src/shared/assets/icons/reviewWrite/minus.svg
  src/shared/assets/icons/reviewWrite/nowday.svg
  src/shared/assets/icons/reviewWrite/old.svg
  src/shared/assets/icons/reviewWrite/overallIcon.svg
  src/shared/assets/icons/reviewWrite/plus.svg
  src/shared/assets/icons/reviewWrite/selectedcheckbox.svg
  src/shared/assets/icons/reviewWrite/slider.svg
  src/shared/assets/icons/reviewWrite/star.svg
  src/shared/assets/icons/reviewWrite/starEmpty.svg
  src/shared/assets/icons/reviewWrite/starhalf.svg
  src/shared/assets/icons/reviewWrite/thumb.svg
  src/shared/assets/icons/reviewWrite/trashicon.svg
  src/shared/components/CustomPagination.jsx
  src/shared/components/ReviewStyle.js
Labels: ✨ Feature

#120 Fix: 후기 작성 모달 UI 수정 (#119)
  src/features/level/ui/LevelTabSection.jsx
  src/features/review/modal/reviewDataList.js
  src/features/review/ui/EscapeResultDetails.jsx
  src/features/review/ui/FlexibleRangeSelector.jsx
  src/features/review/ui/RangeItem.jsx
  src/features/review/ui/ReviewDropdown.jsx
  src/features/review/ui/ReviewFirst.jsx
  src/features/review/ui/ReviewLast.jsx
  src/features/review/ui/ReviewSecond.jsx
  src/features/review/ui/ReviewThird.jsx
  src/features/review/ui/VisitDatePicker.jsx
  src/shared/components/InfoBox.jsx
  src/shared/components/ReviewStyle.js
Labels: 🐞 BugFix

#122 Feat: 전체 검색 페이지 UI 임시 구현, API 연결(#121)
  src/app/App.jsx
  src/features/genre/ui/GenreContentSection.jsx
  src/features/level/ui/LevelContentSection.jsx
  src/features/search/api/getSearchAPI.js
  src/pages/SerachPage.jsx
Labels: ✨ Feature, 📬 API
